# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    goals: 'clean install package'